### ISSUE TITLE
Crash while leaving page

### ISSUE THREAD

**Issue by JanVais** [MileyHollenberg/XamarinPainter#11]
While leaving the page this is the error that occurs and crashes my app.

03-15 15:48:53.622 I/MonoDroid( 7258): UNHANDLED EXCEPTION:
03-15 15:48:53.665 I/MonoDroid( 7258): System.NullReferenceException: Object reference not set to an instance of an object.
03-15 15:48:53.666 I/MonoDroid( 7258):   at Painter.Droid.PainterView.OnSaveInstanceState () [0x00058] in <780ae2f32e584118ae9f191c45a50f1e>:0 
03-15 15:48:53.666 I/MonoDroid( 7258):   at Android.Views.View.n_OnSaveInstanceState (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <95d915721ad748108ff096dce8f8f32c>:0 
03-15 15:48:53.666 I/MonoDroid( 7258):   at (wrapper dynamic-method) System.Object.56(intptr,intptr)

**Comment by MileyHollenberg** [comment]
Merged, will create a new build as soon as I can
